### ISSUE TITLE
monaco-editor 0.13.1 is not supported.

### ISSUE THREAD

**Issue by tamayika** [Microsoft/monaco-editor-webpack-plugin#12]
repro: https://github.com/tamayika/monaco-webpack-test

commands:
```sh
npm i
npm run build
```

result:
```sh
PS F:\work\node\monaco-webpack-test> npm run build

> monaco-webpack-test@1.0.0 build F:\work\node\monaco-webpack-test
> webpack --config webpack.config.js

F:\work\node\monaco-webpack-test\node_modules\webpack-cli\bin\webpack.js:448
                                throw err;
                                ^

Error: Cannot find module 'monaco-editor\esm\vs\editor\contrib\quickFix\quickFixCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.require.resolve (F:\work\node\monaco-webpack-test\node_modules\v8-compile-cache\v8-compile-cache.js:162:23)
    at resolveMonacoPath (F:\work\node\monaco-webpack-test\node_modules\monaco-editor-webpack-plugin\index.js:35:18)
    at use.options.pre.featurePaths.map (F:\work\node\monaco-webpack-test\node_modules\monaco-editor-webpack-plugin\index.js:110:51)
    at Array.map (<anonymous>)
    at createLoaderRules (F:\work\node\monaco-webpack-test\node_modules\monaco-editor-webpack-plugin\index.js:110:31)
    at MonacoWebpackPlugin.apply (F:\work\node\monaco-webpack-test\node_modules\monaco-editor-webpack-plugin\index.js:64:19)
    at webpack (F:\work\node\monaco-webpack-test\node_modules\webpack\lib\webpack.js:37:12)
    at processOptions (F:\work\node\monaco-webpack-test\node_modules\webpack-cli\bin\webpack.js:436:16)
    at yargs.parse (F:\work\node\monaco-webpack-test\node_modules\webpack-cli\bin\webpack.js:512:3)
    at Object.parse (F:\work\node\monaco-webpack-test\node_modules\yargs\yargs.js:552:18)
    at F:\work\node\monaco-webpack-test\node_modules\webpack-cli\bin\webpack.js:217:8
    at Object.<anonymous> (F:\work\node\monaco-webpack-test\node_modules\webpack-cli\bin\webpack.js:514:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (F:\work\node\monaco-webpack-test\node_modules\webpack\bin\webpack.js:80:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

I found some esm monaco-editor module disappeared compared to 0.12.0.
features.js must be changed  or monaco-editor emit bug?

**Comment by tamayika** [comment]
ping @alexandrudima

**Comment by alexandrudima** [comment]
Sorry about that. `monaco-editor-webpack-plugin@1.2.0` published
