### ISSUE TITLE
angular-cli ejected webpack.config.js throw exception

### ISSUE THREAD

**Issue by Renhj90520** [microsoft/monaco-editor-webpack-plugin#6]
I get the webpack.config.js by using angular-cli command ng eject --force, and add this plugin into the plugins section, but when I run npm start it throws the following exception, how could I solve this.

TypeError: Cannot read property 'make' of undefined
    at AddWorkerEntryPointPlugin.apply (E:\user\vscprojects\monaco-editor\node_modules\monaco-editor-webpack-plugin\plugins\AddWorkerEntryPointPlugin.js:16:20)
    at plugins.forEach (E:\user\vscprojects\monaco-editor\node_modules\monaco-editor-webpack-plugin\index.js:82:12)
    at Array.forEach (<anonymous>)
    at addCompilerPlugins (E:\user\vscprojects\monaco-editor\node_modules\monaco-editor-webpack-plugin\index.js:80:11)
    at MonacoWebpackPlugin.apply (E:\user\vscprojects\monaco-editor\node_modules\monaco-editor-webpack-plugin\index.js:67:5)
    at Compiler.apply (E:\user\vscprojects\monaco-editor\node_modules\tapable\lib\Tapable.js:375:16)
    at webpack (E:\user\vscprojects\monaco-editor\node_modules\webpack\lib\webpack.js:33:19)
    at startDevServer (E:\user\vscprojects\monaco-editor\node_modules\webpack-dev-server\bin\webpack-dev-server.js:367:16)
    at processOptions (E:\user\vscprojects\monaco-editor\node_modules\webpack-dev-server\bin\webpack-dev-server.js:350:5)
    at Object.<anonymous> (E:\user\vscprojects\monaco-editor\node_modules\webpack-dev-server\bin\webpack-dev-server.js:495:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)

**Comment by antoniopol06** [comment]
Any update on this? I have the same problem.

**Comment by VincentBel** [comment]
@Renhj90520 @antoniopol06 see #5.

**Comment by Louis-7** [comment]
@VincentBel Works for me.

**Comment by alexdima** [comment]
I believe this has been fixed in the meantime.
